# Form implementation generated from reading ui file 'HelpWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg

class Ui_HelpWindow(object):
    def __init__(self):
        super().__init__()

    def setupUi(self, HelpWindow):
        HelpWindow.setObjectName("HelpWindow")
        HelpWindow.resize(640, 480)
        self.gridLayout = QtWidgets.QGridLayout(HelpWindow)
        self.gridLayout.setObjectName("gridLayout")
        # self.graph = pg.GraphicsLayoutWidget(parent=HelpWindow)
        # self.graph.setObjectName("YGraph")
        print("ASD")
        # self.gridLayout.addWidget(self.plt, 0, 0, 1, 1)
        print("DSA")
        # self.graph.addItem(self.plt)

        self.retranslateUi(HelpWindow)
        QtCore.QMetaObject.connectSlotsByName(HelpWindow)

    def retranslateUi(self, HelpWindow):
        _translate = QtCore.QCoreApplication.translate
        HelpWindow.setWindowTitle(_translate("HelpWindow", "HelpWindow"))
